<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array<int, string>
     */
    protected $except = [
        "/register",
        "/getUser",
        "/currentUser",
        "/uploadFile",
        "/uploadMessageFile",
        "/createStore",
        "/login",
        "/adminUpdateUser",
        "/adminUpdateProduct",
        "/addProduct",
        "/addProductMedia",
        "/storeTransaction",
        "/editStore",
        "/getMessages",
        "/getUserMessages",
        "/updateMessage",
        "/createMessage",
        "/getPlan",
        "/getStoreProducts",
        "/likeStore",
        "/likeProduct",
        "/getStoreLikes",
        "/getProductLikes",
        "/getStoreRating",
        "/rateStore",
        "/getProductRating",
        "/rateProduct",
        "/getProducts",
        "/createBoomerang",
        "/getBoomerangs",
        "/createEvent",
        "/updateEvent",
        "/deleteEvent",
        "/addEventMedia",
        "/getEventMedia",
        "/deleteEventMedia",
        "/deleteProduct",
        "/deleteBoomerang",
        "/storeSubscription",
        "/getMyTransactions",
        "/updateTransaction",
        "/incrementStoreVisits",
        "/getProductComments",
        "/saveProductComment",
        "/getStoreComments",
        "/saveStoreComments",
        "/saveFollower",
        "/getFollowers",
        "/deleteFollower",
        "/deleteFollowing",
        "/getStories",
        "/getStores",
        "/getMyBanks",
        "/getMyTransfers",
        "/resolveAccountDetails",
        "/createRecepient",
        "/initiatePaystackTransfer",
        "/finalizePaystackTransfer",
        "/verifyPaystackTransfer",
        "/listPaystackTransfer",
        "/fetchPaystackTransfer",
        "/addBank",
        "/deleteBank",
        "/getUserOrders",
        "/getStoreOrders",
        "/updateOrder",
        "/registerEvent",
        "/getLogistic",
        "/addLogistic",
        "/updateLogistic",
        "/deleteLogistic",
        "/getLogisticDestination",
        "/addLogisticDestination",
        "/updateLogisticDestination",
        "/deleteLogisticDestination",
        "/googleCallback",
        "/twitterCallback",
        "/getTwitterToken",
        "/twitterRedirect",
        "/facebookCallback",
        "/linkedinCallback",
    ];
}
